apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myaapp
    spec:
      containers:
      - name: myapp
        image: ttl.sh/programmerinyourarea/myapp:2h
        ports:
        - containerPort: 4444
